[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
fs_permissions = [{ access = "read", path = "./circuit/test/fixtures" }]
optimizer = true
optimizer_runs = 100
evm_version = "shanghai"

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[lint]
ignore = ["unsafe-typecast", "mixed-case-variable", "unaliased-plain-import", "unwrapped-modifier-logic", "erc20-unchecked-transfer"]

