name = "0x4a6f686e"
surname = "0x446f65"
age = "18"
address = "0x70617269732c203137617272"
wallet = "0x6d5e982A63B9E4055B7b7CfBAC25ba908061e1A5"
country_code = "10"
kyc_face = "1"
investor_type = "1"
max_amount = "1000000"
nonce = "1"
salt = "0xd1359c703c1d7a1d1429f96f40b"
merkle_path = ["0x00", "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864", "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1", "0x18f43331537ee2af2e3d758d50f72106467c6eea50371dd528d57eb2b856d238"]
path_indices = ["0", "0", "0", "0"]
merkle_root = "0x05de0db30e5b12d705199ed6ea191ef7d3108e89529deb364f5bbfe3859ec730"
nullifier = "0x1a7f6c7ffcf90645d011edafab9f7b17be2c3b3f6195c9819dceacde25e37434"
recipient = "0xABCDEF"
sender = "0x6d5e982A63B9E4055B7b7CfBAC25ba908061e1A5"
transfer_amount = "500000"
